

/* 자격시험 */
CREATE TABLE TEST (
	cert_name VARCHAR2(100) NOT NULL, /* 이름 */
	begin_date DATE NOT NULL, /* 시작일 */
	end_date DATE NOT NULL, /* 마감일 */
	section VARCHAR2(100) NOT NULL, /* 구분 */
	codeno VARCHAR2(100) NOT NULL
);

CREATE UNIQUE INDEX PK_TEST
	ON TEST (
		cert_name ASC,
		begin_date ASC,
		end_date ASC
	);

ALTER TABLE TEST
	ADD
		CONSTRAINT PK_TEST
		PRIMARY KEY (
			cert_name,
			begin_date,
			end_date
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원 */
CREATE TABLE MEMBER (
	id VARCHAR2(100) NOT NULL, /* 아이디 */
	password VARCHAR2(100) NOT NULL, /* 비밀번호 */
	name VARCHAR2(100) NOT NULL, /* 이름 */
	type VARCHAR2(100) NOT NULL, /* 유형 */
	auth VARCHAR2(100) NOT NULL, /* 등급 */
	certificate VARCHAR2(1000) /* 자격증 */
);

CREATE UNIQUE INDEX PK_MEMBER
	ON MEMBER (
		id ASC
	);

ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			id
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 기술 */
CREATE TABLE SKILL (
	name VARCHAR2(100) NOT NULL, /* 기술이름 */
	descript LONG NOT NULL /* 설명 */
);

CREATE UNIQUE INDEX PK_SKILL
	ON SKILL (
		name ASC
	);

ALTER TABLE SKILL
	ADD
		CONSTRAINT PK_SKILL
		PRIMARY KEY (
			name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원보유기술 */
CREATE TABLE MEMBER_SKILL (
	id VARCHAR2(100) NOT NULL, /* 아이디 */
	name VARCHAR2(100) NOT NULL /* 기술이름 */
);

CREATE UNIQUE INDEX PK_MEMBER_SKILL
	ON MEMBER_SKILL (
		id ASC,
		name ASC
	);

ALTER TABLE MEMBER_SKILL
	ADD
		CONSTRAINT PK_MEMBER_SKILL
		PRIMARY KEY (
			id,
			name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 직무 */
CREATE TABLE JOB (
	name VARCHAR2(100) NOT NULL, /* 직무이름 */
	descript LONG NOT NULL /* 설명 */
);

CREATE UNIQUE INDEX PK_JOB
	ON JOB (
		name ASC
	);

ALTER TABLE JOB
	ADD
		CONSTRAINT PK_JOB
		PRIMARY KEY (
			name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 채용공고 */
CREATE TABLE OFFER (
	no NUMBER NOT NULL, /* 게시물번호 */
	begin_date DATE NOT NULL, /* 시작일 */
	end_date DATE NOT NULL, /* 마감일 */
	title VARCHAR2(100) NOT NULL, /* 제목 */
	content LONG NOT NULL, /* 내용 */
	ci_img VARCHAR2(100) NOT NULL, /* 이미지 */
	corporate_id VARCHAR2(100) /* 아이디(기업회원) */
);

CREATE UNIQUE INDEX PK_OFFER
	ON OFFER (
		no ASC
	);

ALTER TABLE OFFER
	ADD
		CONSTRAINT PK_OFFER
		PRIMARY KEY (
			no
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원선택직무 */
CREATE TABLE MEMBER_JOB (
	name VARCHAR2(100) NOT NULL, /* 직무이름 */
	id VARCHAR2(100) NOT NULL /* 아이디 */
);

CREATE UNIQUE INDEX PK_MEMBER_JOB
	ON MEMBER_JOB (
		name ASC,
		id ASC
	);

ALTER TABLE MEMBER_JOB
	ADD
		CONSTRAINT PK_MEMBER_JOB
		PRIMARY KEY (
			name,
			id
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원별-추천공고 */
CREATE TABLE MEMBER_RECOM_OFFER (
	offer_no NUMBER NOT NULL, /* 게시물번호 */
	id VARCHAR2(100) NOT NULL, /* 아이디 */
	type VARCHAR2(100) NOT NULL /* 추천유형 */
);

CREATE UNIQUE INDEX PK_MEMBER_RECOM_OFFER
	ON MEMBER_RECOM_OFFER (
		offer_no ASC,
		id ASC
	);

ALTER TABLE MEMBER_RECOM_OFFER
	ADD
		CONSTRAINT PK_MEMBER_RECOM_OFFER
		PRIMARY KEY (
			offer_no,
			id
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 채용공고-요구사항 */
CREATE TABLE OFFER_SPECS (
	offer_no NUMBER NOT NULL, /* 게시물번호 */
	job_name VARCHAR2(100) NOT NULL, /* 직무이름 */
	skill_name VARCHAR2(100) NOT NULL, /* 기술이름 */
	seq VARCHAR2(100) /* 순번 */
);

CREATE UNIQUE INDEX PK_OFFER_SPECS
	ON OFFER_SPECS (
		offer_no ASC,
		job_name ASC,
		skill_name ASC
	);

ALTER TABLE OFFER_SPECS
	ADD
		CONSTRAINT PK_OFFER_SPECS
		PRIMARY KEY (
			offer_no,
			job_name,
			skill_name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원별-채용공고 */
CREATE TABLE MEMBER_OFFER (
	offer_no NUMBER NOT NULL, /* 게시물번호 */
	id VARCHAR2(100) NOT NULL /* 아이디 */
);

CREATE UNIQUE INDEX PK_MEMBER_OFFER
	ON MEMBER_OFFER (
		offer_no ASC,
		id ASC
	);

ALTER TABLE MEMBER_OFFER
	ADD
		CONSTRAINT PK_MEMBER_OFFER
		PRIMARY KEY (
			offer_no,
			id
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 회원별-자격시험일정 */
CREATE TABLE MEMBER_TEST (
	id VARCHAR2(100) NOT NULL, /* 아이디 */
	cert_name VARCHAR2(100) NOT NULL, /* 이름 */
	begin_date DATE NOT NULL, /* 시작일 */
	end_date DATE NOT NULL /* 마감일 */
);

CREATE UNIQUE INDEX PK_MEMBER_TEST
	ON MEMBER_TEST (
		id ASC,
		cert_name ASC,
		begin_date ASC,
		end_date ASC
	);

ALTER TABLE MEMBER_TEST
	ADD
		CONSTRAINT PK_MEMBER_TEST
		PRIMARY KEY (
			id,
			cert_name,
			begin_date,
			end_date
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 직무마일스톤 */
CREATE TABLE JOB_MILESTONE (
	name VARCHAR2(100) NOT NULL, /* 마일스톤이름 */
	job_name VARCHAR2(100) NOT NULL, /* 직무이름 */
	seq NUMBER NOT NULL, /* 순번 */
	descript LONG NOT NULL /* 설명 */
);

CREATE UNIQUE INDEX PK_JOB_MILESTONE
	ON JOB_MILESTONE (
		name ASC,
		job_name ASC
	);

ALTER TABLE JOB_MILESTONE
	ADD
		CONSTRAINT PK_JOB_MILESTONE
		PRIMARY KEY (
			name,
			job_name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 직무기술 */
CREATE TABLE JOB_SKILL (
	job_name VARCHAR2(100) NOT NULL, /* 직무이름 */
	skill_name VARCHAR2(100) NOT NULL /* 기술이름 */
);

CREATE UNIQUE INDEX PK_JOB_SKILL
	ON JOB_SKILL (
		job_name ASC,
		skill_name ASC
	);

ALTER TABLE JOB_SKILL
	ADD
		CONSTRAINT PK_JOB_SKILL
		PRIMARY KEY (
			job_name,
			skill_name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

/* 공통코드 */
CREATE TABLE CODE (
	attribute VARCHAR2(100) NOT NULL, /* 속성명 */
	codeno NUMBER NOT NULL, /* 코드번호 */
	codename VARCHAR2(100) NOT NULL /* 코드명 */
);

CREATE UNIQUE INDEX PK_CODE
	ON CODE (
		attribute ASC,
		codeno ASC
	);

ALTER TABLE CODE
	ADD
		CONSTRAINT PK_CODE
		PRIMARY KEY (
			attribute,
			codeno
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_SKILL
	ADD
		CONSTRAINT FK_MEMBER_SKILL
		FOREIGN KEY (
			id
		)
		REFERENCES MEMBER (
			id
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_SKILL
	ADD
		CONSTRAINT FK_SKILL_TO_MEMBER_SKILL
		FOREIGN KEY (
			name
		)
		REFERENCES SKILL (
			name
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE OFFER
	ADD
		CONSTRAINT FK_OFFER
		FOREIGN KEY (
			corporate_id
		)
		REFERENCES MEMBER (
			id
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_JOB
	ADD
		CONSTRAINT FK_MEMBER_JOB
		FOREIGN KEY (
			id
		)
		REFERENCES MEMBER (
			id
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_JOB
	ADD
		CONSTRAINT FK_JOB_TO_MEMBER_JOB
		FOREIGN KEY (
			name
		)
		REFERENCES JOB (
			name
		)
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_RECOM_OFFER
	ADD
		CONSTRAINT FK_OFFER_TO_MEMBER_RECOM_OFFER
		FOREIGN KEY (
			offer_no
		)
		REFERENCES OFFER (
			no
		)
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_RECOM_OFFER
	ADD
		CONSTRAINT FK_MEMBER_RECOM_OFFER
		FOREIGN KEY (
			id
		)
		REFERENCES MEMBER (
			id
		)
		ON DELETE CASCADE
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE OFFER_SPECS
	ADD
		CONSTRAINT FK_OFFER_SPECS
		FOREIGN KEY (
			offer_no
		)
		REFERENCES OFFER (
			no
		)
		ON DELETE CASCADE
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE OFFER_SPECS
	ADD
		CONSTRAINT FK_OFFER_SPECS2
		FOREIGN KEY (
			job_name
		)
		REFERENCES JOB (
			name
		)
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE OFFER_SPECS
	ADD
		CONSTRAINT FK_OFFER_SPECS3
		FOREIGN KEY (
			skill_name
		)
		REFERENCES SKILL (
			name
		)
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_OFFER
	ADD
		CONSTRAINT FK_MEMBER_OFFER
		FOREIGN KEY (
			offer_no
		)
		REFERENCES OFFER (
			no
		)
		ON DELETE CASCADE
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_OFFER
	ADD
		CONSTRAINT FK_MEMBER_OFFER2
		FOREIGN KEY (
			id
		)
		REFERENCES MEMBER (
			id
		)
		ON DELETE CASCADE
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_TEST
	ADD
		CONSTRAINT FK_MEMBER_TEST
		FOREIGN KEY (
			id
		)
		REFERENCES MEMBER (
			id
		)
		ON DELETE CASCADE
		NOT DEFERRABLE
		INITIALLY IMMEDIATE
		ENABLE
		VALIDATE;

ALTER TABLE MEMBER_TEST
	ADD
		CONSTRAINT FK_MEMBER_TEST2
		FOREIGN KEY (
			cert_name,
			begin_date,
			end_date
		)
		REFERENCES TEST (
			cert_name,
			begin_date,
			end_date
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE JOB_MILESTONE
	ADD
		CONSTRAINT FK_JOB_MILESTONE
		FOREIGN KEY (
			job_name
		)
		REFERENCES JOB (
			name
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE JOB_SKILL
	ADD
		CONSTRAINT FK_JOB_SKILL
		FOREIGN KEY (
			job_name
		)
		REFERENCES JOB (
			name
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;

ALTER TABLE JOB_SKILL
	ADD
		CONSTRAINT FK_JOB_SKILL2
		FOREIGN KEY (
			skill_name
		)
		REFERENCES SKILL (
			name
		)
		ON DELETE CASCADE
		DEFERRABLE
		INITIALLY DEFERRED
		ENABLE
		VALIDATE;